export const sideList = [
  { type: "h2", text: "Skills:" },
  { type: "h3", text: "Web Development:" },
  { text: "html" },
  { text: "CSS" },
  { text: "SASS" },
  { text: "Javascript, Typescript" },
  { text: "React.js" },
  { text: "Next.js: pages, app routers" },
  { text: "Node.js, Express.js" },
  { text: "Nest.js" },
  { text: "Mongo/Mongoose" },
  { text: "MySQL, Postgres" },
  { text: "Prisma ORM" },
  { text: "Redux Toolkit Query" },
  { text: "React Query" },
  { text: "MobX" },
  { text: "react-admin" },
  {
    text: "Firebase: Authentication, Storage, Firestore Database, Cloud Messaging",
  },
  { text: "GraphQL" },
  { text: "Hasura" },
  { text: "Agenda" },
  { text: "WebSockets" },
  { text: "Tailwind" },
  { text: "Shadcn/ui" },
  { text: "Flowbite" },
  { text: "Material UI" },
  {
    text: "UI features: dark theme, horizontal swiping, pagination, comments tree, tooltips",
  },
  { text: "Forms: react-hook-form, Zod, input masking" },
  { text: "Tables: tanstack/react-table, sorting, filtering, pagination" },
  { text: "TinyMCE rich text editor" },
  { text: "Image uploading: Cloudinary, Firebase" },
  { text: "Email sending: Nodemailer, Resend, Mailersend" },
  { text: "Template engines: Handlebars, Pug" },
  { text: "Manual QA/QC, TestRail" },
  { text: "React Testing Library, Jest" },
  { text: "Postman, Insomnia, Thunder Client" },
  { text: "Gulp" },
  { text: "Figma" },
  { text: "JS parsing, Puppeteer" },
  { text: "Stripe" },
  { text: "Jira" },
  { text: "Git: Github, Gitlab" },
  { text: "Docker" },
  { type: "h3", text: "Data analysis:" },
  { text: "Python: Pandas, NumPy, Matplotlib, SciPy" },
  { text: "Mathematica, Maple" },
  { text: "Tableau" },
  { text: "Excel, Google Sheets, PowerPoint" },
  { type: "h3", text: "Soft skills:" },
  { text: "Agile: Kanban, Scrum" },
  { text: "GTD" },
  { text: "Teamwork" },
  { text: "Cryptocurrencies" },
  { text: "Communications: Telegram, Discord, Google Meet" },
  { type: "h3", text: "Science:" },
  {
    text: "Mathematics in the volume, necessary for theoretical physics: Calculus, Linear algebra, Group Theory",
  },
  { text: "Theoretical Physics: Quantum Mechanics in non-linear spaces" },
  { type: "h3", text: "Languages:" },
  {
    text: "Ukrainian, Russian: native",
  },
  { text: "English: C1-C2" },
  { text: "Polish: B1-B2" },
];
