export const sideList = [
  { type: "h2", text: "Skills:", textUA: "Навичкі:" },
  { type: "h3", text: "Web Development:", textUA: "Веб-розробка" },
  { text: "html" },
  { text: "CSS" },
  { text: "SASS" },
  { text: "Javascript, Typescript" },
  { text: "React.js" },
  { text: "Next.js: Pages, App routers" },
  { text: "Node.js, Express.js" },
  { text: "Nest.js" },
  { text: "Mongo/Mongoose" },
  { text: "MySQL, Postgres" },
  { text: "Prisma ORM" },
  { text: "Type ORM" },
  { text: "Drizzle ORM" },
  { text: "Redux Toolkit Query" },
  { text: "React Query" },
  { text: "MobX" },
  { text: "Redis" },
  {
    text: "WordPress: custom posts, custom components, custom API endpoints",
    textUA: "WordPress: кастомні пости, компоненти, АПІ",
  },
  { text: "PHP for WordPress" },
  { text: "react-admin" },
  {
    text: "Firebase: Authentication, Storage, Firestore Database, Cloud Messaging",
    textUA: "Firebase: Аутентифікація, зберігання файлів, Cloud Messaging",
  },
  { text: "GraphQL: Apollo client, Apollo server" },
  { text: "Hasura" },
  { text: "Agenda" },
  { text: "WebSockets" },
  {
    text: "Translation: i18next, next-intl",
    textUA: "Переклади: i18next, next-intl",
  },
  { text: "axios" },
  { text: "Tailwind" },
  { text: "Shadcn/ui" },
  { text: "Flowbite" },
  { text: "Material UI" },
  {
    text: "UI features: dark theme, horizontal swiping, pagination, comments tree",
    textUA:
      "UI фічі: темна тема, горизонтальне свайпання, паджинація, дерево коментарів",
  },
  {
    text: "Forms: react-hook-form, Zod, input masking",
    textUA: "Форми: react-hook-form, Zod, маска вводу",
  },
  {
    text: "Tables: tanstack/react-table, react-admin, sorting, filtering, pagination",
    textUA:
      "Таблиці: tanstack/react-table, react-admin, сортування, фільтрація, паджинація",
  },
  {
    text: "TinyMCE rich text editor",
    textUA: "TinyMCE розширенний текстовий редактор",
  },
  {
    text: "Image uploading: Cloudinary, Firebase",
    textUA: "Завантаження зображень: Cloudinary, Firebase",
  },
  {
    text: "Email sending: Nodemailer, Resend, Mailersend",
    textUA: "Розсилка емейлів: Nodemailer, Resend, Mailersend",
  },
  { text: "Template engines: Handlebars, Pug" },
  { text: "Manual QA/QC, TestRail" },
  { text: "React Testing Library, Jest" },
  { text: "Postman, Insomnia, Thunder Client" },
  { text: "Gulp" },
  { text: "Figma" },

  { text: "JS parsing, Puppeteer" },
  { text: "Stripe" },

  { text: "Git: Github, Gitlab" },
  { text: "Docker" },
  { type: "h3", text: "Data analysis:", textUA: "Аналіз Данних" },
  { text: "Python: Pandas, NumPy, Matplotlib, SciPy" },
  { text: "Mathematica, Maple" },
  { text: "Tableau" },
  { text: "Excel, Google Sheets, PowerPoint" },
  { type: "h3", text: "Science:", textUA: "Наука" },
  {
    text: "Mathematics in the volume, necessary for theoretical physics: Calculus, Linear algebra, Group Theory",
    textUA:
      "Математика в об'ємі, необхідному для теоретичної фізики: Вища Математика, Лінійна Алгебра, Теорія Груп",
  },
  {
    text: "Theoretical Physics: GRT, Quantum Mechanics in non-linear spaces",
    textUA: "Теоретична Фізика: Квантова механіка в нелінійних просторах",
  },
  { type: "h3", text: "Soft skills:" },
  { text: "Agile: Kanban, Scrum" },
  { text: "GTD" },
  { text: "Teamwork" },
  { text: "Cryptocurrencies", textUA: "Криптовалюти" },
  { type: "h3", text: "Communications:", textUA: "Комунікації:" },
  { text: "Jira" },
  { text: "Discord" },
  { text: "Google Meet" },
  { text: "Miro" },
  { text: "Telegram" },

  { type: "h3", text: "Languages:", textUA: "Мови" },
  {
    text: "Ukrainian, Russian: native",
    textUA: "Українська, Російська: рідні",
  },
  { text: "English: C1-C2", textUA: "Англійська: C1-C2" },
  { text: "Polish: B1-B2", textUA: "Польська: B1-B2" },
];
